# ~/.ticker.yaml
show-tags: true
show-fundamentals: true
show-separator: true
interval: 10
watchlist:
  - BUSXF
  - BTC-USD
  - ETH-USD
  - XLM-USD
lots:
  - symbol: "AMC"
    quantity: 37
    unit_cost: 17.25
  - symbol: "DBO"
    quantity: 25
    unit_cost: 5.14
  - symbol: "OXY"
    quantity: 7
    unit_cost: 12.865
  - symbol: "VET"
    quantity: 6
    unit_cost: 3.61
  - symbol: "SLV"
    quantity: 1
    unit_cost: 41.50
  - symbol: "EXPR"
    quantity: 2
    unit_cost: 5.75
  - symbol: "LPCN"
    quantity: 100
    unit_cost: 1.85
